### ISSUE TITLE
test the 4.4.1

### ISSUE THREAD

**Issue by martinit18** [martinit18/nested_fit#23]

**Comment by martinit18** [comment]
Tests passed: 
- synthetic gaussian: random_walk, slice sampling, uniform
- synthetic gaussian error bars (slice sampling only)
- synthetic gaussian sets (slice sampling only)
- TEST_GAUSS
- TEST_EGGBOX (slice sampling) agglomerative not working
- gauss_bg (slice sampling only)
- 4gauss_bg (slice sampling, random_walk, knn, mean-shift)

**Comment by martinit18** [comment]
@Lune, can you test the EGGBOX with agglomerative, if you can, and the HARMONIC?

**Comment by lPrimemaster** [comment]
@martinit18 There is another way of making the tests without using a folder for each type of search. Will fix this on my next change.
