### ISSUE TITLE
modify nested_res.py to make it compatible with the new input

### ISSUE THREAD

**Issue by martinit18** [martinit18/nested_fit#53]

**Comment by lPrimemaster** [comment]
@martinit18 Hi Martino I don't know if you've seen my message at #38 but are we to keep the new input file strategy with the likelihood function? We better decide before we do this. Cheers,

**Comment by lPrimemaster** [comment]
Experimental fix in [42ca10f](https://github.com/martinit18/nested_fit/commit/42ca10f43338f3de8d8e794c1e695364aa4363d1).
