### ISSUE TITLE
Bug of DEBUG option in cmake file. After the precompilation, the make compilation fails

### ISSUE THREAD

**Issue by martinit18** [martinit18/nested_fit#66]

**Comment by martinit18** [comment]
The error message is the following with gfortran in Mac Os with M1 pro:

[ 51%] Linking Fortran executable /Users/martino/Owncloud/CNRS/work/programs/nested_fit/actual_version_with_git/bin/nested_fit4.5.2
Undefined symbols for architecture arm64:
  "__mcount", referenced from:
      _wofz_ in WOFZ.f.o
      _curfit_ in curfit.f.o
      _fpback_ in fpback.f.o
      _fpbspl_ in fpbspl.f.o
      _fpchec_ in fpchec.f.o
      _fpcurf_ in fpcurf.f.o
      _fpdisc_ in fpdisc.f.o
      ...
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[2]: *** [/Users/martino/Owncloud/CNRS/work/programs/nested_fit/actual_version_with_git/bin/nested_fit4.5.2] Error 1
make[1]: *** [CMakeFiles/nested_fit4.5.2.dir/all] Error 2
make: *** [all] Error 2

**Comment by lPrimemaster** [comment]
Hi @martinit18. Did you `rm -rf *`? The build directory before running? I believe this is because of a linker name being set on the `-pg` flag. And as you disabled it, you could have some leftover files laying around.

**Comment by lPrimemaster** [comment]
For me the `-DDEBUG=ON` flag works normally.

**Comment by martinit18** [comment]
It looks a compiler problem.... I will wait for updates

**Comment by martinit18** [comment]
Compiler problem solved after compiler update
